nnoremap <space>b :buffers<cr>:b<space>
nnoremap <space>e :b#<cr>
nnoremap <space>w :w<cr>
nnoremap <space>q :qa<cr>
inoremap jf <esc>
cnoremap jf <c-c>

set ts=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set relativenumber
